### ISSUE TITLE
Get the list of countries

### ISSUE THREAD

**Issue by nagaharish** [thecodecrate/city-state#1]
Hi,
This gem is vey much helpful to me.
But I wanted to know the list of countires. Is there a method to get the complete list of countries so that I can use that.
Because  to get the states I need to pass the country code hence to get the country code I need the countries list.
Thank you in Advance.

**Comment by loureirorg** [comment]
great idea! I just implemented it. 

Update your gemfile (`bundle update` if using Rails) and call with `CS.countries`

**Comment by nagaharish** [comment]
Hi,
Thanks a lot for adding this. It will be veryhelpful for me.
