### ISSUE TITLE
Problem with states and cities, only getting country name with those methods

### ISSUE THREAD

**Issue by svonborries** [thecodecrate/city-state#4]
Hello, 
Thanks for the gem, it's really necessary in web development...
But I have a problem with the methods... they only answer me the country name...
**This is my development enviroment:**
Mac platform
_RVM
Ruby 2.1.1
Rails 4.1.6_

let me show you the results of my rails console:

```
2.1.1 :043 > CS.get
     => {:AD=>"Andorra", :AE=>"United Arab Emirates", :AF=>"Afghanistan", :AG=>"Antigua and Barbuda",
```

Wich is OK!

Then when i try to send the Bolivia code :BO even the US code...

```
    2.1.1 :044 > CS.get :bo
        => "Bolivia" 
    2.1.1 :045 > CS.get :us
        => "United States" 
```

OK... lets try the other methods:

```
2.1.1 :046 > CS.states(:us)
 => "United States" 
2.1.1 :047 > CS.states(:bo)
 => "Bolivia" 
```

OK... I'll spent some time checking the code and I went to my gem directory and I found this file **GeoLite2-City-Locations-en.csv**, at the begining i tought maybe this is a permission problem, i changed the **cmod to 777** just to test... and the answer is the same...
Then i tryed to get the Cities:

```
2.1.1 :051 > CS.cities(:bo, :s)
 => [] 
```

and then i tryed to do the same with US:

```
CS.cities(:us, :or)
 => [] 
2.1.1 :061 > CS.cities(:us, :nv)
 => [] 
```

then i try a random State code...

```
CS.cities(:us, :pa)
TypeError: no implicit conversion of Symbol into Integer
    from /Users/svonborries/.rvm/gems/ruby-2.1.1@seru/gems/city-state-0.0.12/lib/city-state.rb:145:in `[]'
    from /Users/svonborries/.rvm/gems/ruby-2.1.1@seru/gems/city-state-0.0.12/lib/city-state.rb:145:in `cities'
    from (irb):62
```

Am I missing something??? or maybe it's something related to my SO (Snow Leopard)

Please give me a hand with this... I really want to use yout gem.

Have a great Day,

Sergio,

**Comment by loureirorg** [comment]
Hi Sergio,

Are you using the 0.0.12 version? The 0.0.11 version was with a similar problem, which was corrected on 0.0.12.

Can you check with `bundle show | grep city-state` and put the results here?

**Comment by svonborries** [comment]
Hello,

Yes I'm using the latest version... take a look!

bundle show | grep city-state
- city-state (0.0.12)

**Comment by loureirorg** [comment]
I think that I fixed the bug. Can you run a `bundle update`, check if it's using the 0.0.13 version (`bundle show | grep city-state`) and check if the bug still exists?

---

What I have changed:

Although I can reproduce the bug here, I found a problem in the code that can be related with this bug:

I done this awful thing [here](https://github.com/loureirorg/city-state/blob/master/lib/city-state.rb#L39):

``` ruby
@countries = @cities = @states = {}
```

Originally I have this code:

``` ruby
@countries = {}
@cities = {}
@states = {}
```

and I had refactored it in order to shrunk the code, but what I really should have done was:

``` ruby
@countries, @states, @cities = [{}, {}, {}]
```

Just for curiosity, `@countries = @cities = @states = {}` will create aliases between these 3 variables. So if you change one of them, you change the rest of them.

``` ruby
> a = b = {}
> a
{}
> a[:a] = 1
> b
{:a=>1}
```

**Comment by svonborries** [comment]
Hello,
Now is working quite good!
Take a look...

2.1.1 :008 > CS.get :bo
 => {:B=>"El Beni", :C=>"Departamento de Cochabamba", :H=>"Departamento de Chuquisaca", :L=>"Departamento de La Paz", :N=>"Departamento de Pando", :O=>"Oruro", :P=>"Departamento de Potosi", :S=>"Departamento de Santa Cruz", :T=>"Departamento de Tarija"} 
2.1.1 :009 > CS.get :bo, :s
 => ["Anillo", "Aroma", "Cotoca", "Santa Cruz"] 
2.1.1 :010 > 

At least in my development enviroment it's great!

Thank you very much,

Ser...
