### ISSUE TITLE
Typo correction "Tithari" should be changed to "Ithari" for Nepal 

### ISSUE THREAD

**Issue by sajanbasnet75** [thecodecrate/city-state#40]

**Comment by sajanbasnet75** [comment]
Country > Nepal
State >  Province 1
City > Tithari should be chaned to Ithari

**Comment by loureirorg** [comment]
On the new version, 0.1.0, you can create a `db\cities-lookup.yml` with this content:
```yaml
NP:
  P1:
    "Tithari": "Ithari"
```

This will rename Tithari to Ithari.
