### ISSUE TITLE
`CS.countries` is giving `undefined method 'exists?' for File:Class` error

### ISSUE THREAD

**Issue by anmol-kumar0815** [thecodecrate/city-state#61]
I have followed the following steps to install city-state:
1. Added city-state in gem file.
2. Run bundle install.

Then I tried to get the list of countries in rails console by:
```
CS.countries
```
<img width="1278" alt="Screenshot 2023-08-19 at 3 10 28 PM" src="https://github.com/thecodecrate/city-state/assets/67572237/7916cb95-dc3b-4b42-b98d-0759f4e99307">

**Comment by anmol-kumar0815** [comment]
This issue occurs because I had installed 0.1.0 version in which exists? method has been used, and now this method has been depreciated.

To resolve this issue make sure you have installed 1.1.0 version. You can lock the gem version by adding the below line in your gem file:
```
gem "city-state", "1.1.0"
```

**Comment by loureirorg** [comment]
Good catch. Thanks, @anmol-kumar0815.

I restricted the version 0.x series to Ruby 2 only ([release 0.1.1](https://github.com/thecodecrate/city-state/releases/tag/v0.1.1))

This guarantees that users using Ruby 3 and higher always use the latest 1.x series, even when not explicitly defining the version on `Gemfile`.
